name: tarsier_http_parser
description: A lightweight and flexible Dart HTTP client designed for making API calls with dynamic response parsing.
version: 1.0.1
homepage: https://github.com/marianz-bonfire/tarsier_http_parser
repository: https://github.com/marianz-bonfire/tarsier_http_parser
issue_tracker: https://github.com/marianz-bonfire/tarsier_http_parser/issues

topics:
  - tarsier
  - response
  - parser
  - http
  - api

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

environment:
  sdk: ^3.2.1

dependencies:
  http: ^1.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0

screenshots:
  - description: The package logo.
    path: assets/logo.png