name: tarsier_http_parser
description: A lightweight and flexible Dart HTTP client designed for making API calls with dynamic response parsing.
version: 1.0.0
homepage: https://github.com/marianz-bonfire/tarsier_http_parser
repository: https://github.com/marianz-bonfire/tarsier_http_parser
issue_tracker: https://github.com/marianz-bonfire/tarsier_http_parser/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
